apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: login
          image: 519852036875.dkr.ecr.us-west-1.amazonaws.com/jishoy-ecr:jish
          ports:
            - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - nodePort: 31479
      port: 8002
      targetPort: 8002
